### ISSUE TITLE
CLI tooling w/ Click

### ISSUE THREAD

**Issue by Scarly-Cat** [Scarly-Cat/lamia#20]
> https://click.palletsprojects.com/en/7.x/

Just putting this here to keep it on the radar, tbh.

**Comment by cbondurant** [comment]
I feel like this would be rather useful to go ahead and implement, given that we have the entire folder of scripts that would probably be well suited to be used in a Click style cli tool.

Perhaps for this we create a `lamia-cli` that utilizes click commands. Though this does slowly get close to copying the flask way of doing things.
