### ISSUE TITLE
Rename instance to community or site

### ISSUE THREAD

**Issue by Scarly-Cat** [Scarly-Cat/lamia#21]
So. What does the word instance even mean in the context of a web server?

For the sake of clarity, we should probably standardize to community or site, to be honest. Server is also a possibility, but it's similarly ambiguous tbh as compared to instance (since a single server's IP may map to multiple hosted sites powered by lamia).

Thoughts? If none, then I'll just do this at some point prior to 0.1.0.

**Comment by trwnh** [comment]
Voicing support for "site" as the genericized term for instances. "Domain" is also technically accurate in DNS-based systems that use the root domain as a namespace, but this is about as complicated as explaining software instantiation to most people. "Site", on the other hand, has seen generic usage for decades, and is thus widely understood. Federation is therefore a network of sites that can communicate with each other (semantically accurate and easily understood).
